/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.ConversorMonedas;
import clases.HerramientasFormularios;




/**
 *
 * @author Sergio
 */
public class InterfazConversorMonedas extends javax.swing.JFrame {
    HerramientasFormularios ditribuidor = new HerramientasFormularios();
    ConversorMonedas metodo = new ConversorMonedas();
    /**
     * Creates new form Bienvenida
     */
    public InterfazConversorMonedas() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        jScrollPane.setBorder(null);
        setIconImage(ditribuidor.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backgroundBlackTitulo = new javax.swing.JPanel();
        labelTituloProgram = new javax.swing.JLabel();
        backgroundBlack = new javax.swing.JPanel();
        logoDev = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JToggleButton();
        copyRight = new javax.swing.JLabel();
        backgroundBilletes = new javax.swing.JLabel();
        bienvenida = new javax.swing.JLabel();
        imagenOtraMoneda = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        introduccion = new javax.swing.JTextArea();
        labelOtraMoneda = new javax.swing.JLabel();
        imagenPesoMexicano = new javax.swing.JLabel();
        labelPesoMexicano = new javax.swing.JLabel();
        btnOtramoneda = new javax.swing.JToggleButton();
        btnPesoMexicano = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Monedas");
        setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundBlackTitulo.setBackground(new java.awt.Color(0, 0, 0));
        backgroundBlackTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTituloProgram.setBackground(new java.awt.Color(0, 0, 0));
        labelTituloProgram.setFont(new java.awt.Font("Roboto Medium", 3, 14)); // NOI18N
        labelTituloProgram.setForeground(new java.awt.Color(255, 255, 255));
        labelTituloProgram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloProgram.setLabelFor(background);
        labelTituloProgram.setText("Conversor de Monedas");
        backgroundBlackTitulo.add(labelTituloProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        background.add(backgroundBlackTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 200, 30));

        backgroundBlack.setBackground(new java.awt.Color(0, 0, 0));
        backgroundBlack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sg.png"))); // NOI18N
        backgroundBlack.add(logoDev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(backgroundBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 120, 120));

        btnRegresar.setBackground(new java.awt.Color(255, 36, 0));
        btnRegresar.setFont(new java.awt.Font("Roboto Black", 1, 11)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setFocusable(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        background.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 100, 30));

        copyRight.setFont(new java.awt.Font("Roboto Light", 2, 11)); // NOI18N
        copyRight.setForeground(new java.awt.Color(255, 255, 255));
        copyRight.setText("© Copyrigth Sergio González - 2023");
        background.add(copyRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        backgroundBilletes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/billetes.png"))); // NOI18N
        background.add(backgroundBilletes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 280, 380));

        bienvenida.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        bienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ConversorMonedaslogo.png"))); // NOI18N
        bienvenida.setText(" ¡BIENVENIDO!");
        background.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        imagenOtraMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/otramonedaPeso150.png"))); // NOI18N
        background.add(imagenOtraMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 150, -1));

        introduccion.setEditable(false);
        introduccion.setColumns(20);
        introduccion.setFont(new java.awt.Font("Roboto Medium", 3, 12)); // NOI18N
        introduccion.setLineWrap(true);
        introduccion.setText("Programa que convierte pesos mexicanos en cualquier divisas mostradas o inversamente, actualizadas al momento.");
        introduccion.setToolTipText("");
        introduccion.setWrapStyleWord(true);
        introduccion.setBorder(null);
        introduccion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        introduccion.setFocusable(false);
        introduccion.setRequestFocusEnabled(false);
        jScrollPane.setViewportView(introduccion);

        background.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 50));

        labelOtraMoneda.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelOtraMoneda.setText("Otra moneda a peso mexicano");
        background.add(labelOtraMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        imagenPesoMexicano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pesoOtramoneda150.png"))); // NOI18N
        background.add(imagenPesoMexicano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, -1));

        labelPesoMexicano.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        labelPesoMexicano.setText("Peso mexicano a otra moneda");
        background.add(labelPesoMexicano, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        btnOtramoneda.setBackground(new java.awt.Color(14, 144, 173));
        btnOtramoneda.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnOtramoneda.setForeground(new java.awt.Color(255, 255, 255));
        btnOtramoneda.setText("Click");
        btnOtramoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtramonedaActionPerformed(evt);
            }
        });
        background.add(btnOtramoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 100, 30));

        btnPesoMexicano.setBackground(new java.awt.Color(0, 99, 65));
        btnPesoMexicano.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnPesoMexicano.setForeground(new java.awt.Color(255, 255, 255));
        btnPesoMexicano.setText("Click");
        btnPesoMexicano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesoMexicanoActionPerformed(evt);
            }
        });
        background.add(btnPesoMexicano, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ditribuidor.getOtherInterfaz(this,new InterfazPrincipal());
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPesoMexicanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesoMexicanoActionPerformed
        ditribuidor.getOtherInterfaz(this,new InterfazConversorPesosOtraMoneda());
    }//GEN-LAST:event_btnPesoMexicanoActionPerformed

    private void btnOtramonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtramonedaActionPerformed
         ditribuidor.getOtherInterfaz(this,new InterfazConversorOtraMonedaPesos());
    }//GEN-LAST:event_btnOtramonedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConversorMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConversorMonedas().setVisible(true);
                
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel backgroundBilletes;
    private javax.swing.JPanel backgroundBlack;
    private javax.swing.JPanel backgroundBlackTitulo;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JToggleButton btnOtramoneda;
    private javax.swing.JToggleButton btnPesoMexicano;
    private javax.swing.JToggleButton btnRegresar;
    private javax.swing.JLabel copyRight;
    private javax.swing.JLabel imagenOtraMoneda;
    private javax.swing.JLabel imagenPesoMexicano;
    private javax.swing.JTextArea introduccion;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelOtraMoneda;
    private javax.swing.JLabel labelPesoMexicano;
    private javax.swing.JLabel labelTituloProgram;
    private javax.swing.JLabel logoDev;
    // End of variables declaration//GEN-END:variables
    
    


}
