/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import clases.ConversorMonedas;
import clases.HerramientasFormularios;


/**
 *
 * @author Sergio
 */
public class InterfazPrincipal extends javax.swing.JFrame {
HerramientasFormularios distribuidor = new HerramientasFormularios();
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jScrollPane.setBorder(null);
        setIconImage(distribuidor.getIconImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backgroundTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        introduccion = new javax.swing.JTextArea();
        backgroundTemperatura = new javax.swing.JPanel();
        imagenPeso1 = new javax.swing.JLabel();
        labelPeso1 = new javax.swing.JLabel();
        backgroundPeso = new javax.swing.JPanel();
        imagenPeso = new javax.swing.JLabel();
        labelPeso = new javax.swing.JLabel();
        backgroundMedicion = new javax.swing.JPanel();
        imagenMedicion = new javax.swing.JLabel();
        labelMedicion = new javax.swing.JLabel();
        backgroundMonedas = new javax.swing.JPanel();
        imagenMonedas = new javax.swing.JLabel();
        labelMonedas = new javax.swing.JLabel();
        copyRight = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Converter");
        setResizable(false);

        background.setBackground(new java.awt.Color(201, 233, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundTitulo.setBackground(new java.awt.Color(44, 117, 228));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sg10.png"))); // NOI18N
        jLabel1.setText("          ¡BIENVENIDO!");

        introduccion.setEditable(false);
        introduccion.setBackground(new java.awt.Color(44, 117, 228));
        introduccion.setColumns(20);
        introduccion.setFont(new java.awt.Font("Roboto Medium", 3, 12)); // NOI18N
        introduccion.setForeground(new java.awt.Color(255, 255, 255));
        introduccion.setLineWrap(true);
        introduccion.setText("Programa que dispone de varios conversores de diferentes tipos favor de seleccionar uno dando click en el recuadro.");
        introduccion.setToolTipText("");
        introduccion.setWrapStyleWord(true);
        introduccion.setBorder(null);
        introduccion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        introduccion.setFocusable(false);
        introduccion.setRequestFocusEnabled(false);
        jScrollPane.setViewportView(introduccion);

        javax.swing.GroupLayout backgroundTituloLayout = new javax.swing.GroupLayout(backgroundTitulo);
        backgroundTitulo.setLayout(backgroundTituloLayout);
        backgroundTituloLayout.setHorizontalGroup(
            backgroundTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTituloLayout.createSequentialGroup()
                .addGroup(backgroundTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundTituloLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(backgroundTituloLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        backgroundTituloLayout.setVerticalGroup(
            backgroundTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        background.add(backgroundTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        backgroundTemperatura.setBackground(new java.awt.Color(151, 214, 236));
        backgroundTemperatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundTemperatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundTemperaturaMouseClicked(evt);
            }
        });
        backgroundTemperatura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPeso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convertidorTemperaturaPrincipal.png"))); // NOI18N
        backgroundTemperatura.add(imagenPeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 140));

        labelPeso1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        labelPeso1.setText("Conversor Temperatura");
        backgroundTemperatura.add(labelPeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        background.add(backgroundTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 190, 170));

        backgroundPeso.setBackground(new java.awt.Color(217, 217, 217));
        backgroundPeso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundPeso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenPeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convertidorPesoPrincipal.png"))); // NOI18N
        backgroundPeso.add(imagenPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 138));

        labelPeso.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        labelPeso.setText("Conversor Peso");
        backgroundPeso.add(labelPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        background.add(backgroundPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 190, 170));

        backgroundMedicion.setBackground(new java.awt.Color(255, 87, 87));
        backgroundMedicion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundMedicion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenMedicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convertidorMedicionPrincipal.png"))); // NOI18N
        backgroundMedicion.add(imagenMedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 138));

        labelMedicion.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        labelMedicion.setText("Conversor Distancia");
        backgroundMedicion.add(labelMedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        background.add(backgroundMedicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, 170));

        backgroundMonedas.setBackground(new java.awt.Color(246, 223, 184));
        backgroundMonedas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backgroundMonedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMonedasMouseClicked(evt);
            }
        });
        backgroundMonedas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenMonedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/convertidorMonedaPrincipal.png"))); // NOI18N
        backgroundMonedas.add(imagenMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 138));

        labelMonedas.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        labelMonedas.setText("Conversor Monedas");
        backgroundMonedas.add(labelMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        background.add(backgroundMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, 170));

        copyRight.setFont(new java.awt.Font("Roboto Light", 3, 11)); // NOI18N
        copyRight.setForeground(new java.awt.Color(255, 255, 255));
        copyRight.setText("© Copyrigth Sergio González - 2023");
        background.add(copyRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMonedasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMonedasMouseClicked
    this.distribuidor.getOtherInterfaz(this, new InterfazConversorMonedas());
    }//GEN-LAST:event_backgroundMonedasMouseClicked

    private void backgroundTemperaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundTemperaturaMouseClicked
        this.distribuidor.getOtherInterfaz(this, new InterfazConversorTemperatura());
    }//GEN-LAST:event_backgroundTemperaturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundMedicion;
    private javax.swing.JPanel backgroundMonedas;
    private javax.swing.JPanel backgroundPeso;
    private javax.swing.JPanel backgroundTemperatura;
    private javax.swing.JPanel backgroundTitulo;
    private javax.swing.JLabel copyRight;
    private javax.swing.JLabel imagenMedicion;
    private javax.swing.JLabel imagenMonedas;
    private javax.swing.JLabel imagenPeso;
    private javax.swing.JLabel imagenPeso1;
    private javax.swing.JTextArea introduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelMedicion;
    private javax.swing.JLabel labelMonedas;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JLabel labelPeso1;
    // End of variables declaration//GEN-END:variables
}
